//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroMunge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThirdPtyDocs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThirdPtyDocs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroMunge.ThirdPtyDocs", typeof(ThirdPtyDocs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2016, Alexandre Mutel  
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///
        ///2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license_markdig {
            get {
                return ResourceManager.GetString("license_markdig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, including without limitation the rights to
        ///use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
        ///the Software, and to permit persons to whom the Software is furnished to do so,
        ///subject to the following conditions:
        ///
        ///The above copyrig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license_NewtonsoftJson {
            get {
                return ResourceManager.GetString("license_NewtonsoftJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2014, Ershov Andrey
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permiss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license_prettybin {
            get {
                return ResourceManager.GetString("license_prettybin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License: Custom License  
        ///MICROSOFT SOFTWARE LICENSE TERMS  
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK
        ///________________________________
        ///These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///
        ///- updates,
        ///- supplements,
        ///- Internet-based services, and 
        ///- support servi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license_WindowsAPICodePack {
            get {
                return ResourceManager.GetString("license_WindowsAPICodePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several fantastic pieces of [free](http://www.gnu.org/philosophy/free-sw.html) and [open-source](https://opensource.org/) software 
        ///have helped extend the functionality of Zero Munge in many useful ways.
        ///
        ///Third-party software that is part of Zero Munge:.
        /// </summary>
        internal static string preamble {
            get {
                return ResourceManager.GetString("preamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* GitHub stylesheet for MarkdownPad (http://markdownpad.com) */
        ////* Author: Nicolas Hery - http://nicolashery.com */
        ////* Version: b13fe65ca28d2e568c6ed5d7f06581183df8f2ff */
        ////* Source: https://github.com/nicolahery/markdownpad-github */
        ///
        ////* RESET
        ///=============================================================================*/
        ///
        ///html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stylesheet {
            get {
                return ResourceManager.GetString("stylesheet", resourceCulture);
            }
        }
    }
}
